version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
services:
  - postgresql
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6
    - postgresql-client-9.6
    
docker:
      - image: postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgresql
          POSTGRES_DB: ${FastDelivery}-test
          POSTGRES_PASSWORD: "ifpe"
env:
  global:
  - PGPORT=5433
