version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
build:
    docker:
      - image: circleci/jdk8:0.1.1
      - image: postgres:9.6
        environment:
          POSTGRES_USER: postgresql
          POSTGRES_DB: ${FastDelivery}-test
          POSTGRES_PASSWORD: "ifpe"
env:
  global:
  - PGPORT=5433
