version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
build:
    docker:
      - image: circleci/jdk8:0.1.1
      - image: postgres:9.6
        environment:
          POSTGRES_USER: postgresql
          POSTGRES_DB: ${FastDelivery}-test
          POSTGRES_PASSWORD: "ifpe"
before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-9.6 postgresql-client-9.6
  - sudo cp /etc/postgresql/{9.6,9.6}/main/pg_hba.conf
  - sudo service postgresql restart 11  
before_script:
  - psql --version
  - psql -c 'CREATE DATABASE {{FastDelivery}};' -U postgres
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
  - cp config/database.yml.travis config/database.yml
script: bundle exec rake spec
services:
  - postgresql
addons:
  postgresql: "9.6"
